name: builder-dockerfile
# trigger on PR from these branches
on:
  pull_request:
    branches:
      - master
      - develop
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: docker build -t vindi .
