name: builder
on:
  pull_request:
    branches:
      - master
      - develop
jobs:
  dockerfile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: docker build -t vindi .
