name: linter
on: 
  - push
  - pull_request
jobs:
  dockerfile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: hadolint
      run: docker run --rm -i 
        -v "$PWD"/.hadolint.yaml:/opt/.config/hadolint.yaml
        -e XDG_CONFIG_HOME=/opt/.config
        hadolint/hadolint < Dockerfile
  shell:
    runs-on: ubuntu-latest
    steps:
      - name: shellcheck
        uses: azohra/shell-linter@v0.3.0
        with:
          path: "install.sh,bin/vindi"
