name: linter-dockerfile
on: 
  - push
  - pull_request
jobs:
  commitsar:
    name: lint-dockerfile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: lint
      run: docker run --rm -i hadolint/hadolint < Dockerfile
