name: publisher-dockerhub
on:
  create:
    tags: 
      - '**'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to dockerhub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: dnice/vindi
          username: dnice
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_names: true
      - name: Publish to dockerhub as latest
        if: startsWith(github.ref, 'refs/tags/v')
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: dnice/vindi
          username: dnice
          password: ${{ secrets.DOCKER_PASSWORD }}
